#%RAML 1.0
title: Slack types
types:
  Message:
    type: object
    properties:
      type?: string
      ts?: string
      user?: string
      text?: string
      is_starred?: boolean
      wibblr?: boolean
    example:
      type: "message"
      ts: "1358546515.000007"
      user: "U2147483896"
      text: "Hi!"
      is_starred: false
      wibblr: true
  ChannelsHistory:
    type: object
    properties:
      ok?: boolean
      latest?: string
      messages?: Message[]
      has_more: boolean
    example:
      ok: true
      latest: "latest"
      messages:
        - type: "type"
          ts: "ts"
          user: "Mark"
          text: "Hi!"
          is_starred: false
          wibblr: true
      has_more: false
  ChannelItem:
    type: object
    properties:
      id?: string
      name?: string
      created?: integer
      creator?: string
      is_archived?: boolean
      is_member?: boolean
      num_members?: number
      topic?:
        type: object
        properties:
          value?: string
          creator?: string
          last_set?: integer
      members?: string[]
      purpose?:
        type: object
        properties:
          value?: string
          creator?: string
          last_set?: string
    example:
      id: "C024BE91L"
      name: "fun"
      created: "1360782804"
      creator: "U024BE7LH"
      is_archived: false
      is_member: false
      num_members: 6
      topic:
        value: "Fun times"
        creator: "U024BE7LV"
        last_set: "1369677212"
      purpose:
        value: "This channel is for fun"
        creator: "U024BE7LH"
        last_set: "1360782804"
  Channels:
    type: object
    properties:
      ok?: boolean
      channels?: ChannelItem[]
    example:
      - id: "C024BE91L"
        name: "fun"
        created: "1360782804"
        creator: "U024BE7LH"
        is_archived: false
        is_member: false
        num_members: 6
        topic:
          value: "Fun times"
          creator: "U024BE7LV"
          last_set: "1369677212"
        purpose:
          value: "This channel is for fun"
          creator: "U024BE7LH"
          last_set: "1360782804"
  Channel:
    type: object
    properties:
      id?: string
      name?: string
      is_channel?: boolean
      created?: integer
      creator?: string
      is_archived?: boolean
      is_general?: boolean
      is_member?: boolean
      last_read?: string
      latest:
        type: object
        properties:
          user?: string
          type?: string
          subtype?: string
          text?: string
          ts?: string
      unread_count?: number
      unread_count_display?: number
      members?: string[]
      topic?:
        type: object
        properties:
          value?: string
          creator?: string
          last_set?: integer
      purpose?:
        type: object
        properties:
          value?: string
          creator?: string
          last_set?: string
    example:
      id: "C024BE91L"
      name: "fun"
      created: "1360782804"
      creator: "U024BE7LH"
      is_archived: false
      is_channel: true
      is_member: false
      is_archived: true
      is_general: false
      last_read: "1401383885.000061"
      topic:
        value: "Fun times"
        creator: "U024BE7LV"
        last_set: "1369677212"
      purpose:
        value: "This channel is for fun"
        creator: "U024BE7LH"
        last_set: "1360782804"
  ChannelsInvite:
    type: object
    properties:
      ok?: boolean
      channel: Channel
    example:
      ok: true
      channel:
        id: "C024BE91L"
        name: "fun"
        created: "1360782804"
        creator: "U024BE7LH"
        is_archived: false
        is_channel: true
        is_member: false
        is_archived: true
        is_general: false
        last_read: "1401383885.000061"
        topic:
          value: "Fun times"
          creator: "U024BE7LV"
          last_set: "1369677212"
        purpose:
          value: "This channel is for fun"
          creator: "U024BE7LH"
          last_set: "1360782804"
  Ok:
    type: object
    properties:
      ok?: boolean
    example:
      ok: true
  FileObj:
    type: object
    properties:
      ok?: boolean
      file?:
        type: object
    example:
      ok: false
  Purpose:
    type: object
    properties:
      ok?: boolean
      purpose?: string
    example:
      ok: true
      purpose: "This is the new purpose!"
  ChatOk:
    type: object
    properties:
      ok?: boolean
      ts?: string
      channel?: string
    example:
      ok : true
      ts : "1405895017.000506"
      channel : "C024BE91L"
  EmojiList:
    type: object
    properties:
      ok?: boolean
      emoji?:
        type: object
        properties:
          bowtie?: string
          squirrel?: string
          shipit?: string
    example:
      ok: true
      emoji:
        bowtie : "https://my.slack.com/emoji/bowtie/46ec6f2bb0.png"
        squirrel : "https://my.slack.com/emoji/squirrel/f35f40c0e0.png"
        shipit : "alias:squirrel"
  ImsItem:
    type: object
    properties:
      id?: string
      user?: string
      created?: number
      is_user_deleted?: boolean
    example:
      id: "C024BE91L"
      user: "U024BE7LH"
      created: "1360782804"
      is_user_deleted: false
  Ims:
    type: object
    properties:
      ok?: boolean
      ims: ImsItem[]
    example:
      ok: true
      ims:
        - id: "C024BE91L"
          user: "U024BE7LH"
          created: "1360782804"
          is_user_deleted: false
  StarFileItem:
    type: object
    properties:
      type?: string
      file?: string
      comment?: string
    example:
      type: "file_comment"
      file: ""
      comment: ""
  StarChannelItem:
    type: object
    properties:
      type?: string
      channel?: string
      message?: string
    example:
      type: "message"
      channel: "C2147483705"
      message: ""
  StarList:
    type: object
    properties:
      ok?: boolean
      items: (StarFileItem | StarChannelItem) []
      paging?:
        type: object
        properties:
          count?: number
          total?: number
          page?: number
          pages?: number
    example:
      ok: true
      items:
        - type: "file_comment"
          file: ""
          comment: ""
        - type: "message"
          channel: "C2147483705"
          message: ""
      paging:
        count: 242
        tatal: 420
        page: 4
        pages: 429
