#%RAML 1.0 ResourceType
get?:
  queryParameters:
    channel:
      description: <<resourceName>> to fetch history for.
      required: true
      example: C1234567890
    ts:
      description: Timestamp of the most recently seen message.
      required: true
      example: "1234567890.123456"
  responses:
    200:
      body:
        application/json:
          type: types.Ok
